trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest


variables:
  - group: aws-terraform-ci
    terraformWorkingDir: terraform/azure

stages:

- stage: Validate
  displayName: Terraform Validate
  jobs:
  - job: terraform_validate
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.5.7'

    - task: AzureCLI@2
      displayName: Terraform Validate (Azure CLI Auth)
      inputs:
        azureSubscription: azure-terraform-plan
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(terraformWorkingDir)
          terraform init
          terraform fmt -check -recursive
          terraform validate

- stage: Plan
  displayName: Terraform Plan
  dependsOn: Validate
  jobs:
  - job: terraform_plan
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.5.7'

    - task: AzureCLI@2
      displayName: Terraform Plan (Azure CLI Auth)
      inputs:
        azureSubscription: azure-terraform-plan
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(terraformWorkingDir)
          terraform init
          terraform plan -out=tfplan

    - publish: $(terraformWorkingDir)/tfplan
      artifact: terraform-plan



# -------------------------
# AWS PLAN STAGE
# -------------------------
- stage: Plan_AWS
  displayName: Terraform Plan (AWS)
  dependsOn: Validate
  jobs:
  - job: terraform_plan_aws
    displayName: Terraform Plan AWS
    variables:
      - group: aws-terraform-ci
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.5.7'

    - task: Bash@3
      displayName: Terraform Plan (AWS)
      inputs:
        targetType: inline
        script: |
          set -e
          cd terraform/aws

          echo "Verifying AWS identity..."
          aws sts get-caller-identity

          echo "Initializing Terraform backend..."
          terraform init -reconfigure -input=false

          terraform fmt -check -recursive
          terraform validate
          terraform plan -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    - publish: terraform/aws/tfplan
      displayName: Publish Terraform Plan Artifact (AWS)
      artifact: terraform-plan-aws
